### ISSUE TITLE
What is GAME_SERVER_URL set to on your .env file?

### ISSUE THREAD

**Issue by Roeefl** [colyseus/colyseus-monitor#13]
.env.example would be highly appreciated

**Comment by seiyria** [comment]
Looking at [this](https://github.com/colyseus/colyseus-monitor/blob/14d86f7ae0704d7c2005a77aeaec8ccd680033c0/src/frontend/services.ts#L3), it defaults to the current URL (ie, if you have your server on `server.game.com` it will look for the server there). Presumably you only need to set it if you're running `colyseus-monitor` locally, but not on your game server.
