### ISSUE TITLE
The number of clients is different between list room and detail room UI.

### ISSUE THREAD

**Issue by vinkent420** [colyseus/colyseus-monitor#22]
Hi @endel, first of all I wanna say many thanks for building a great tool Colyseus, it helped us a lots.

I'm using colysues monitor to tracking clients, but I'm facing issse the number of clients at list room and detail page are different. I'm using colyseus v 0.14

Here is 2 screenshots:
![image_list_room_1](https://github.com/colyseus/colyseus-monitor/assets/135956574/8299d485-b3d7-4616-9ac9-76eaf930f73d)
![image_room_detail](https://github.com/colyseus/colyseus-monitor/assets/135956574/ff1a8b45-fb4f-449f-835b-6c130d034e89)

Thank @endel and Colyseus community!

**Comment by endel** [comment]
Hi @vinkent420, thank you for the words.

As you're on 0.14 I'm not sure this has been fixed already.

Would it be possible for you to migrate to version 0.15? Cheers

**Comment by vinkent420** [comment]
Ah, I must thank you @endel , that's right.
Ok, I will try to migrate to version 0.15. Cause it take me must upgrade both client as well (both client and server share the colyseus/schema). Will update to you sure if v0.15 already fixed this issue. Cheers
