### ISSUE TITLE
Server crashes when room is disposed from inspection view

### ISSUE THREAD

**Issue by Steditor** [colyseus/colyseus-monitor#24]
When disposing a room by clicking on the button "DISPOSE ROOM" in the inspection view, the colyseus server crashes with the following error:

> TypeError: First argument must be a valid error code number
    at Sender.close ([...]\node_modules\@colyseus\ws-transport\node_modules\ws\lib\sender.js:116:13)
    at WebSocket.close ([...]\node_modules\@colyseus\ws-transport\node_modules\ws\lib\websocket.js:287:18)
    at WebSocketClient.leave ([...]\node_modules\@colyseus\ws-transport\build\WebSocketClient.js:82:14)
    at [...]\node_modules\@colyseus\core\build\Room.js:523:56

I tracked down the error to https://github.com/colyseus/colyseus-monitor/blob/11555cd2e4aa786f3815aac7d75375274a9597cf/src/frontend/components/RoomInspect.tsx#L115 in combination with https://github.com/colyseus/colyseus-monitor/blob/11555cd2e4aa786f3815aac7d75375274a9597cf/src/frontend/components/RoomInspect.tsx#L81 where the `disconnect` method is called with the room id as argument. This room id ends up as argument for `closeCode` in https://github.com/colyseus/colyseus/blob/0e69c0aade7445cdb1dca270d5f7143f478b867d/packages/core/src/Room.ts#L501 which ultimately results in the above error in the ws library.

In comparison, the dispose button in the list view works just fine, because it does not pass any arguments to the `disconnect` method: https://github.com/colyseus/colyseus-monitor/blob/11555cd2e4aa786f3815aac7d75375274a9597cf/src/frontend/components/RoomList.tsx#L83

Removing the room id in the first mentioned code line should probably get rid of the error.

**Comment by endel** [comment]
Thank you for reporting and pointing out your findings @Steditor 🙌 
 Just published `@colyseus/monitor` version `0.15.2`
