### ISSUE TITLE
Feature Request: Sort Clients numerically

### ISSUE THREAD

**Issue by hunkydoryrepair** [colyseus/colyseus-monitor#29]
Currently, the sorting on the "Clients" column is alphabetic, so sorting in reverse order gives 9,99,8,800,...,100,10,1
Which is not very useful. I know the columns are semi dynamic, and won't have type information for the metadata columns, but I think the 'clients' column just needs to be tagged as a 'number' column in MUI

**Comment by endel** [comment]
Thanks for the suggestion @hunkydoryrepair, just released version `0.15.6` allowing to sort both by `clients` and `elapsedTime` 🙌
