### ISSUE TITLE
Monitor doesn't work with Colyseus v0.9.18

### ISSUE THREAD

**Issue by arjunrajskoolbo** [colyseus/colyseus-monitor#6]
After upgrading my colyseus server to v0.9.18, the monitor no longer shows any rooms or clients. It was working fine on 0.9.15. All I get now is the monitor page that isn't populated with any data.

**Comment by endel** [comment]
Nice catch @arjunrajskoolbo, thanks for sharing! Just released `colyseus@0.9.19` to fix this. Cheers!
