### ISSUE TITLE
Monitor doesn't work with Colyseus v0.10.7

### ISSUE THREAD

**Issue by mikhailkuts** [colyseus/colyseus-monitor#7]
Rooms list is empty after room creation

**Comment by endel** [comment]
hey @mikhailkuts, which version of `@colyseus/monitor` as you using? The official examples had a previous version of it installed some weeks ago, I've fixed it quite recently: https://github.com/colyseus/colyseus-examples/commit/4cbd7fdb9d2fca1db5d72f598430afc3b46a65e8

**Comment by mikhailkuts** [comment]
Hi, sorry. I using v0.10.0 monitor from npm.
"@colyseus/monitor": "^0.10.0",

**Comment by mikhailkuts** [comment]
And I cant see any created rooms using this version
