### ISSUE TITLE
v11 negative clients - handler not visible

### ISSUE THREAD

**Issue by Xian55** [colyseus/colyseus-monitor#8]
Hey just updated every colyseus module to v11.

Env:
    "@colyseus/monitor": "^0.11.0",
    "@colyseus/schema": "^0.4.54",
    "@colyseus/social": "^0.11.0",
    "colyseus": "^0.11.0-alpha.4",

1. the `handler` field is blank.
2. The amount of players is negative.
3. Also the elapsedTime shows "less than a second" always.

![monitor_err](https://user-images.githubusercontent.com/367101/63927311-b89b7880-ca4d-11e9-9699-2f6340d11ca4.png)

Tried:
- Reload the page multiple times

Note:
- By opening the room by `Inspect` button shows a valid state of the players amount.

--------- --------- --------- ---------

Update 1:
- By updating the server "colyseus": "^0.11.0-alpha.4", -> "colyseus": "0.11.8" solves the `clients` amount and the time, however the `handler` still not visible

**Comment by endel** [comment]
Thanks for reporting @Xian55. Version `@colyseus/monitor@0.11.5` fixes this.

I've also fixed inspecting rooms without a `state` set, which was causing problems. Now it's okay! Cheers
